"""Create match stats model

Revision ID: 1be7e5af2d2f
Revises: 7469093c6155
Create Date: 2025-01-19 11:15:37.013293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '1be7e5af2d2f'
down_revision: Union[str, None] = '7469093c6155'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matchstatistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('data_id', sa.Integer(), nullable=True),
    sa.Column('livescore_id', sa.Integer(), nullable=True),
    sa.Column('transfermarkt_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('NOT_STARTED', 'FINISHED', name='matchstatus'), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('goal_for', sa.Integer(), nullable=True),
    sa.Column('goal_against', sa.Integer(), nullable=True),
    sa.Column('fouls', sa.Integer(), nullable=True),
    sa.Column('shots', sa.Integer(), nullable=True),
    sa.Column('shots_off_goal', sa.Integer(), nullable=True),
    sa.Column('shots_on_goal', sa.Integer(), nullable=True),
    sa.Column('attacks', sa.Integer(), nullable=True),
    sa.Column('possession', sa.Integer(), nullable=True),
    sa.Column('livescore_xg', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matchstatistics')
    # ### end Alembic commands ###
