version: 1
disable_existing_loggers: False
formatters:
  standard:
    datefmt: "%Y-%m-%d+%H:%M:%S"
    format: "[%(levelname)s - %(asctime)s - %(module)s:%(lineno)d] : %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout
root:
  level: INFO
  handlers:
    - console
  propagate: no
