name: Tests

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup env
        run: |
          mv .env.sample .env
          docker compose build api
          docker compose up -d

      - name: Run lints
        run: |
           docker compose exec api uv run mypy .
           docker compose exec api uv run ruff check . --fix
           docker compose exec api uv run ruff format .

      - name: Run tests
        run: |
          docker compose exec api uv run pytest --cov=.
          docker compose exec api uv run coverage report --show-missing --format=markdown >> $GITHUB_STEP_SUMMARY
          docker compose exec api uv run coverage html
          docker compose exec api uv run coverage report --fail-under=100

      - name: Clean
        run: docker compose down -v --remove-orphans

      - name: Store coverage files
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: app/htmlcov
          retention-days: 5
